"""
export.py
Small helpers to turn session state into a downloadable markdown report.
"""

from datetime import datetime


def build_markdown_report(project_title, project_context, chat_histories):
    """
    Combines the project context and every agent's chat history into a
    single markdown document the student can download and paste into
    their report.
    """
    lines = [
        f"# {project_title or 'NovaMentor Project Report'}",
        "",
        f"_Generated by NovaMentor on {datetime.now().strftime('%Y-%m-%d %H:%M')}_",
        "",
        "## Project Context",
        "",
        project_context or "_No project context provided yet._",
        "",
    ]

    for agent_name, messages in chat_histories.items():
        if not messages:
            continue
        lines.append(f"## {agent_name}")
        lines.append("")
        for msg in messages:
            speaker = "**You:**" if msg["role"] == "user" else f"**{agent_name}:**"
            lines.append(f"{speaker} {msg['content']}")
            lines.append("")

    return "\n".join(lines)
